### ISSUE TITLE
PublishSubject differences between monifu and monix

### ISSUE THREAD

**Issue by DellCliff** [monixio/monix#154]
Just wanted to let you know, that PublishSuject behaves differently in monifu and monix
```
object Main {
  def simulateA(): Unit = {
    println("START")

    import monix.reactive.subjects.PublishSubject
    val context1 = monix.execution.Scheduler.global
    val context = context1

    val aaa1 = PublishSubject[Int]()
    aaa1.foreach(println)(context)

    for {
      i <- Range(0, 2)
    } {
      val r = aaa1.onNext(i)
      println(i, r)
    }
    aaa1.onComplete()

    println("END")
  }

  def simulateB(): Unit = {
    println("START")

    import monifu.reactive.subjects.PublishSubject
    val context1 = monifu.concurrent.Scheduler.apply(scala.concurrent.ExecutionContext.global)
    val context = context1

    val aaa1 = PublishSubject[Int]()
    aaa1.foreach(println)(context)

    for {
      i <- Range(0, 2)
    } {
      val r = aaa1.onNext(i)
      println(i, r)
    }
    aaa1.onComplete()

    println("END")
  }

  def main(args: Array[String]): Unit = {
    simulateA()
    simulateB()
  }
}
```
Produces
```
START
(0,Continue)
1
(1,Continue)
END
START
0
(0,Continue)
1
(1,Continue)
END
Process finished with exit code 0
```

**Comment by alexandru** [comment]
@DellCliff don't worry, it's not the behavior of PublishSubject that changed, but that of `foreach`.

The new `foreach` is translated into `foreachL.runAsync`, where `foreachL` returns a [Task](https://monix.io/docs/2x/eval/task.html) and this `Task` is asynchronous because it is created by means of `Task.unsafeCreate`. I did this because this way we can now return a `CancelableFuture`, so it gives you back something that:

1. allows you to cancel the subscription
2. on the JVM you can block on it if you want, waiting for the end of the stream

In other words, this subscription is now asynchronous and happens on another (logical) thread. So this is why you're missing an event in that sample. It's not the behavior of the `PublishSubject`, which suffered only minor modifications, it's because that `foreach` subscription ends up happening on another thread in parallel.

If you want to fix this particular sample, to be equivalent with version 1 (Monifu), replace this line:

```scala
aaa1.foreach(println)(context)
```

With this one:

```scala
aaa1.doOnNext(println).subscribe()
```

Or more idiomatic for testing purposes:

```scala
aaa1.dump("O").subscribe()
```

BTW, thanks for taking the time to investigate. We need bug reports.

**Comment by DellCliff** [comment]
Thanks for clearing that up. I'm having fun experimenting around with monix so far.
