### ISSUE TITLE
Task Applicative instance doesn't run the tasks in parallel 

### ISSUE THREAD

**Issue by mmollaverdi** [monixio/monix#193]
Combining 2 tasks using monix-cat's applicative instance, results in sequential (monadic) execution of those tasks, as opposed to parallel execution which is what you would expect from an applicative.

E.g. 

```
import monix.cats._
implicitly[Applicative[Task]]

val task1 = Task.apply { log("Started Action1"); 1 }.delayResult(5.seconds).map(x=> { log("Finished Action1"); x } )
val task2 = Task.apply { log("Started Action2"); 2 }.map(x=> { log("Finished Action2"); x } )

val task = (task1 |@| task2).map(_ + _)
val result = Await.result(task.runAsync, 10.seconds)
```

The result I get for a sample run is:
```
2016-07-01T18:38:35.098 - Started Action1
2016-07-01T18:38:40.113 - Finished Action1
2016-07-01T18:38:40.116 - Started Action2
2016-07-01T18:38:40.117 - Finished Action2
```

(Task2 only starts once Task1 has finished)

See the full code example [here](https://github.com/mmollaverdi/free-applicatives-example/blob/258e71417b63fc274725c0cb8c677a68185141c4/src/main/scala/Main.scala).

If I implement an Applicative instance using `Task.mapBoth` though, I get the expected results:

```
object TaskApplicativeInstance {
  implicit val TaskApplicative: Applicative[Task] = new Applicative[Task] {
    override def pure[A](x: A): Task[A] = Task.now(x)
    
    override def ap[A, B](ff: Task[A => B])(fa: Task[A]): Task[B] = Task.mapBoth(ff, fa)((f, a) => f(a))
  }
}
```

I get:
```
2016-07-01T18:44:27.283 - Started Action2
2016-07-01T18:44:27.286 - Started Action1
2016-07-01T18:44:27.286 - Finished Action2
2016-07-01T18:44:32.291 - Finished Action1
```

See the full code example with this custom applicative instance [here](https://github.com/mmollaverdi/free-applicatives-example/blob/6e457c35d5871365d4ed8dafeccf3aadf7efed60/src/main/scala/Main.scala).

**Comment by dialelo** [comment]
Good point @mmollaverdi, you are looking for the [non-deterministic Applicative instance](https://github.com/monixio/monix/blob/5baf85cf10214099b157c8bbf71987e9e09e1201/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L1545).

**Comment by mmollaverdi** [comment]
Thanks @dialelo.

Any reason why that's not the default? Also is there a `cats` applicative version of this?

**Comment by alexandru** [comment]
@mmollaverdi @dialelo so normally all you have to do is:

```scala
import monix.eval.Task.nondeterminism
```

Unfortunately there's a problem for Cats. That applicative builder is using `product` instead of `map2` or `ap`. Which is IMHO a problem with Cats, because `product` is a redundant operation with `map2`. And its default implementation is based on `flatMap`.

I [committed a patch](https://github.com/monixio/monix/commit/7e9177988bc397f46426e7203ddd2977dc444021) that also overrides `product` to use `map2` instead of `flatMap`. Will happen in the next release.

**Comment by mmollaverdi** [comment]
Thanks @alexandru. I appreciate your quick response.

**Comment by mmollaverdi** [comment]
I just tested the example I've linked to above with monix `2.0-RC9`, but unfortunately got the same result.

**Comment by alexandru** [comment]
@mmollaverdi are you sure?

[There is a test](https://github.com/monixio/monix/blob/v2.0-RC9/monix-cats/shared/src/test/scala/monix/cats/ParallelTaskLawsSuite.scala#L41) that ensures the tasks are executed in parallel when using `import monix.eval.Task.nondeterminism`. That test cannot lie.

Also, after running [your sample](https://github.com/mmollaverdi/free-applicatives-example/blob/258e71417b63fc274725c0cb8c677a68185141c4/src/main/scala/Main.scala), along with the required import, I got this output:

```
2016-08-08T09:44:01.819 - Starting
2016-08-08T09:44:01.932 - Started Action2
2016-08-08T09:44:01.933 - Started Action1
2016-08-08T09:44:01.934 - Finished Action2
2016-08-08T09:44:06.944 - Finished Action1
2016-08-08T09:44:06.947 - Result is 3
2016-08-08T09:44:06.947 - Finished
```

That seems to be running in parallel to me.

Do note that `import monix.eval.Task.nondeterminism` is required, because parallelism is not the default and there are really good reasons for that, including performance reasons.

**Comment by alexandru** [comment]
@mmollaverdi btw, sorry for the late response, I've been on vacation :-)

**Comment by mmollaverdi** [comment]
Hmm, thanks @alexandru. Adding `import monix.eval.Task.nondeterminism` fixed it for me as you suggested.

> btw, sorry for the late response, I've been on vacation :-)

No worries at all. I hope you had a good time and thanks for your help.

**Comment by alexandru** [comment]
Cool. Closing the issue for now.
