### ISSUE TITLE
Task timeout doesn't cancel the task which has timed out

### ISSUE THREAD

**Issue by lukestephenson** [monixio/monix#206]
Task.timeout is implemented as https://github.com/monixio/monix/blob/13021b735320ecd76581158716557df0d7d1dcf4/monix-eval/shared/src/main/scala/monix/eval/Task.scala#L486:
```
timeoutTo(after, raiseError(new TimeoutException(s"Task timed-out after $after of inactivity")))
```

and 
```
  def timeoutTo[B >: A](after: FiniteDuration, backup: Task[B]): Task[B] =
    Task.chooseFirstOf(self, backup.delayExecution(after)).map {
      case Left(((a, futureB))) =>
        futureB.cancel()
        a
      case Right((futureA, b)) =>
        futureA.cancel()
        b
    }
```

If the original task succeeds, then the `map` operator will cause the backup (timeout) task to cancel.

However, if the backup (timeout) task completes first, it will return a Task in an error state.  The `map` operator is then short circuited and the original task is not cancelled.

**Comment by alexandru** [comment]
chooseFirstOf should cancel everything in case one task ends in error. I modified it a little in the last release and might have made a mistake.

I'm not at a computer right now. Will confirm later.

Thanks for the report. Do you want to attempt a fix?

**Comment by alexandru** [comment]
@lukestephenson there was a test already that proves the main task is indeed getting canceled, because as I said, `chooseFirstOf` cancels all tasks in case one of them terminates in error. [Link to the test](https://github.com/monixio/monix/blob/706961949820758dcbcfd605426c33ad61adfc74/monix-eval/shared/src/test/scala/monix/eval/TaskChooseFirstOfSuite.scala#L103).

BTW, this happens on master and in the latest version at least. Make sure you're on the latest version.

On the other hand, in case you have modeled a `flatMap` loop, then you may have been bitten by this other issue: https://github.com/monixio/monix/issues/207 - if yes, then a fix is already on master and will be available in the next release.

Cheers,

**Comment by alexandru** [comment]
@lukestephenson doing some cleanup. You can reopen this issue if I missed anything and you can reproduce the problem.
