### ISSUE TITLE
Consuming items without backpressure

### ISSUE THREAD

**Issue by andreaferretti** [monixio/monix#86]
I need to model a scenario like follows. I have a source `s` that emits at its own rate, and various functions are computed on windows on `s`. These are then assembled at the end in a tuple. So the topology looks like

```
s ~> last(n1) ~> op1 ~> m
s ~> last(n2) ~> op2 ~> m
...
s ~> last(nk) ~> opk ~> m
```

(a fan-out followed by a fan-in).

Now, the problem is that the various operations may need a different time to compute. Newer data from `s` is considered more fresh than the previous ones, so I never want to backpressure, but rather skip stale data. I would like to ensure that operations skip whatever inputs they may have missed and keep computing their result on the latest window of data available.

Is there a way to model this kind of behaviour in monifu?

**Comment by alexandru** [comment]
@andreaferretti, in general back-pressure means that you're forced to deal with slow consumers (i.e. pick a strategy instead of pretending that the problem does not exist) and not that you have to slow down the producers. Obviously there are cases in which the producers cannot be slowed down, like in your example.

So what you do is that you use a buffer. If you use a `Channel`, then usage of a buffer *shared* between all observers is implied. You can also insert a buffer anywhere you want and the best location depends on your use case.

Start from [OverflowStrategy](https://github.com/monifu/monifu/blob/master/monifu/shared/src/main/scala/monifu/reactive/OverflowStrategy.scala) for picking a buffer type (for example you may want to buffer everything until the process crashes, or on overflow you might want to drop old events, or new events, or you might want to drop the whole buffer, or attempt to back-pressure the upstream if possible). Then you've got the operators that let you insert this buffer, like `whileBusyBuffer`, or `asyncBoundary`. For something simple and efficient you could just use `whileBusyDrop`.

In your example, you have to choose between using (1) a shared buffer for `s` or (2) or an individual buffer for each of the `last(x)` steps. For (1) the advantage is less RAM usage, plus the `last(x)` consumers will get the same events and at the same time, but the disadvantage is that slower consumers will slow down the faster ones. It really depends on what you want. 

In general the answer to your question is *of course*, but let me know if that answers it, otherwise some code samples would help.

**Comment by andreaferretti** [comment]
Hi alexandru, thank you very much for your suggestions! I will start writing something with the operators that you suggest, and if I should find any obstacle, I will reopen the issue.

**Comment by andreaferretti** [comment]
Just to be sure: am I correct in understanding that the following will give a window on the latest n elements of the observable, without applying any backpressure?

```scala
implicit class WindowedObservable[A](val o: Observable[A]) extends AnyVal {
  def latest(n: Int): Observable[Seq[A]] =
    o.whileBusyBuffer(OverflowStrategy.DropOld(n)).buffer(n, 1)
}
val obs: Observable[A] = ???
val lastest100elements = obs.latest(100)
```

**Comment by alexandru** [comment]
Well yes, it introduces a buffer of 128 elements (it's actually not 100, it rounds it up to the next power of 2 because that makes it more efficient, but that's an implementation detail). And when that buffer is full, the strategy is to start dropping elements. So `onNext` on such a buffer will always be a synchronous `Continue` so the producer doesn't need to wait on anything.
